dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.1"
dotenv: .env
networks:
  goerli:
    verify: True
wallets:
  from_key: ${67e640861802100601f436cd07a736532ae0937f8b83aeb2af844fd7fe21f25f}