dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.1"
dotenv: .env
networks:
  goerli:
    verify: True
  sepolia:
    verify: True
  xdc-testnet:
    verify: True
  Apothem-Testnet:
    verify: True
  xdc-apothem:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}